### ISSUE TITLE
Week3 Assignment Simple Twitter client ready for review

### ISSUE THREAD

**Issue by priyam** [priyam/SimpleTwitterClient#1]
My app for Week 3 Assignment (Simple Twitter Client) is ready for review. Please take a look. /cc @codepathreview @codepath

Thanks,
PC

**Comment by codepathreview** [comment]
:+1: Great work! A few notes after checking out the code:
- Good to see you were able to format the timestamp cleanly (consider externalizing `getCreatedAtPrettyTime` to utils class)
- Nice to see you used the `SwipeRefreshLayout` for easy timeline refreshes
- Good to see you refreshed the timeline after composing a new tweet
- Great job implementing the compose tweet feature as a popup activity
- Consider adding local persistence of tweets by using ActiveAndroid in the `Tweet` and `User`. See the [persistence guide](http://guides.codepath.com/android/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](http://guides.codepath.com/android/ActiveAndroid-Guide) for more details.
-  Nice touch with the character count being displayed while the user composes a tweet 
- Great effort on the UI to make it more twitter branded

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
